---
- name:      rebootComputer
  shell: ( sleep 2 && /sbin/reboot & )
  async: 0
  poll: 0
  ignore_errors: true


- name:      waitForComputer
  become: false
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300