---
# Remove Files
- apt: name={{items}} state=absent purge=yes 
  with_items:
  - transmission
  - hexchat
  - thunderbird
  - pidgin
 

# Install Files
- apt: name={{items}} state=absent purge=yes update_cache=yes
  with_items:
 # Screensavers
  - xscreensaver-gl
  - xscreensaver-gl-extra
  - xscreensaver-screensaver-dizzy
  - xscreensaver-screensaver-webcollage
  - xscreensaver-data-extra
  - rss-glx
