---

- name: Create Symlink to make editing Autostart easier
  file:
      src: '.config/lxsession/LXDE-pi/autostart'
      dest: '/home/pi/autostart'
      state: link

# Remove Files
- apt: state=absent purge=yes name={{item}}
  with_items:
    - transmission
    - hexchat
    - thunderbird
    - pidgin

# Install Files
- apt: state=present name={{item}}
  with_items:
    - python-software-properties
    - htop
    - ufw

- name: Allow OpenSSH though Firewall
  ufw:
    rule: allow
    name: OpenSSH

- name: Enableing UFW
  ufw:
    state: enabled
