---
  - name: Remove unnessary Programs
    apt: state=absent purge=yes name={{item}}
    with_items:
      - transmission
      - hexchat
      - thunderbird
      - pidgin
      - oracle-java8-jdk
      - wolfram-engine
      - deluge
    tags:
      - deploy


  - name: Install required signage packages
    apt: state=present name={{ item }}
    with_items:
      - python-software-properties
      - htop
      - wget
      - curl
      - nano
      - python-pycurl
      - gnome-user-guide
      - yelp-xsl
      - yelp
      - minecraft*
    tags:
      - deploy

  - name: Download and Install Chrome for arm
    get_url: url=https://dl.dropboxusercontent.com/u/87113035/{{ item }} dest=/home/pi/{{ item }}
    apt: deb=/home/pi/{{ item }}
    with_items:
      - chromium-browser-l10n_48.0.2564.82-0ubuntu0.15.04.1.1193_all.deb
      - chromium-browser_48.0.2564.82-0ubuntu0.15.04.1.1193_armhf.deb
      - chromium-codecs-ffmpeg-extra_48.0.2564.82-0ubuntu0.15.04.1.1193_armhf.deb
    tags:
      - deploy
      - chromeArm
