---
- name: Remove unnessary Programs
  apt: state=absent purge=yes name={{item}}
  with_items:
      - libreoffice-*
      - wolfram-engine
      - nuscratch
      - penguinspuzzle
      - piclone
      - htop
      - gksu
      - ephiphany-browser
  tags:
      - deploy

- name: Install required signage packages
  apt: state=present name={{ item }}
  with_items:
      - curl
      - git
  tags:
      - deploy
