---
- name: Ensure NTP (for time syncronization) is installed
  apt: name=ntp state=present
- name: Ensure NTP is running
  service: name=ntpd state=started enabled=yes

- name: Allow access through firewall (iptables)
  iptables: chain=INPUT source=any destination_port={{item}} state=present
  with_items:
    - 22
    - 5099
